### ISSUE TITLE
Contaminants confusion

### ISSUE THREAD

**Issue by monicabritton** [msettles/expHTS#50] opened 2016-03-05 01:08 UTC
Synopsis:  -A works but -c does not. (Matt fixed this in his local repo.)

Complete info:
I created a folder, called contaminants.  In the folder there is a symlink to a fasta file that I downloaded from NCBI (and have already used with bowtie2 and bwa).  When I try to run this command:

expHTS preprocess -t 24 -w -c contaminants -f samples.txt -a 

I get this error message:
Traceback (most recent call last):
  File "/home/msettles/Python_venv/bin/expHTS", line 9, in <module>
    load_entry_point('expHTS==1.0.1.dev2', 'console_scripts', 'expHTS')()
  File "/home/msettles/Python_venv/local/lib/python2.7/site-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/**init**.py", line 18, in main
    expHTS.main()
  File "/home/msettles/Python_venv/local/lib/python2.7/site-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/expHTS.py", line 167, in main
    commands[args.command].execute(args)
  File "/home/msettles/Python_venv/local/lib/python2.7/site-packages/expHTS-1.0.1.dev2-py2.7-linux-x86_64.egg/expHTS/preprocessCMD.py", line 108, in execute
    if os.path.exists(args.contaminatesFolder):
AttributeError: 'Namespace' object has no attribute 'contaminatesFolder'

But the usage also shows -A as contaminants (or adapter contaminants).  So I changed the command to -A and it ran, but I don't think that's correct

Also, it should be spelled "contaminants".

Thanks,

Monica

**Comment by msettles** [comment] 2016-03-05 01:13
These were spelling errors in expHTS.py and preprocessCMD.py I’ve fixed the cause of the error and committed fixes to both master and develop

Matt

**Comment by dstreett** [comment] 2016-03-08 19:12
Thanks, Matt! Just pulled the changes on the servers over here.

**Closed as completed by dstreett** 2016-03-08 19:12 UTC

**Comment by msettles** [comment] 2016-03-09 01:12
Ya! Collaborative development
